services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./public
      dockerfile: Dockerfile
    ports:
      - "5500:80"
    volumes:
      - ./public:/usr/share/nginx/html
